{% set name = "tkinter-tooltip" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tkinter_tooltip-{{ version }}.tar.gz
  sha256: dac8a6720c851936dfea2d96f90920a4dac31b46b78379c5e0ef0b6ed8af2964

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - tktooltip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gnikit/tkinter-tooltip
  summary: An easy and customisable ToolTip implementation for Tkinter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
